### ISSUE TITLE
GPG Key Expired

### ISSUE THREAD

**Issue by Okhoshi** [awein/SleepProxyClient#15]
`W: GPG error: http://repo.weinlein.info unstable InRelease: The following signatures were invalid: EXPKEYSIG 0B99BFAAC8628A6F Andreas Weinlein <andreas.dev@weinlein.info> F471FC607351F8217E5FFD6D0B99BFAAC8628A6F
E: The repository 'http://repo.weinlein.info unstable InRelease' is not signed.`

**Comment by awein** [comment]
Thanks for letting me know. It's great to see that this is still useful and still works but this project is not really maintained anymore for some time now (I don't even use it myself anymore). I would suggest to remove the repo for now. Sorry...

**Comment by awein** [comment]
SleepProxyClient is alive again but there won't be a repo for the time being. `.deb` files will be available on the GitHub release
