### ISSUE TITLE
avahi-browse doesn't discover local services

### ISSUE THREAD

**Issue by lixee** [awein/SleepProxyClient#18]
Just stumbled across this old solution to get wake-on-demand in unraid working, but sadly it's not working for me.
 
Already figured out what the problem seems to be. The script won't get any discovered services. When running "avahi-browse -a" I'm also not able to see my services (smb, ssh, sftp).
 
But when I run avahi-browse on my raspberry pi, the services are visible. So it seems they are getting published correctly on unraid, but my unraid server won't recognise them using the avahi-browse command, which seems to be necessary for the python script to do its thing...

But I have absolutely no idea what could cause this problem :(

**Comment by awein** [comment]
I'm about to bring this project back to live a bit but it's unlikely that `avahi-browse -a` will be removed as a dependency.

`avahi-browse -a` not returning anything is strange. Are you sure that the device you're running this on is on the same network (ethernet) and no firewall is blocking any traffic?

**Comment by lixee** [comment]
avahi-browse -a returns a lot of things on my unraid server except the local services (smb, ssh, sftp), which seems to be necessary for the script to work.

When running avahi-browse -a on any other device in my network I also see the unraid services, so they are getting published.

But I can't figure out why avahi-browse -a won't return the local services, when executed on my unraid server. I already booted a clean configuration, but the problem stays the same.

**Comment by awein** [comment]
Good to hear that you found a way to make this work for you.

I'll close this given it seems to be a Slackware / avahi issue.
