### ISSUE TITLE
Script errors when SPC_RTC_WAKE is not defined

### ISSUE THREAD

**Issue by kanongil** [awein/SleepProxyClient#23]
The `00_sleepproxyclient` script has started erroring after updating to v2.2. Both on `pre` and on `post`.

```
/usr/libexec/elogind/system-sleep/00_sleepproxyclient: line 57: /sys/class/rtc//wakealarm: Permission denied
```

This is caused by faulty `[ -e "/sys/class/rtc/${SPC_RTC_WAKE}" ]` checks, which will pass if `SPC_RTC_WAKE` is `""` or undefined. I suggest you update them to just check for a non-empty value, ie. `[ "${SPC_RTC_WAKE}" != "" ]`. This also means that the assignment to wakelock will error when an invalid value is specified. Currently it will just silently fail.

**Comment by kanongil** [comment]
FYI, I'm currently abusing the silently ignoring "feature" to workaround this issue, with `SPC_RTC_WAKE=none`.

**Comment by awein** [comment]
Hi @kanongil,

thanks for raising this and thanks for the PR. I ended up using a slightly different change and added an additional check instead
